[package]
name = "window"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.winapi]
version = "0.3"
features = ["winuser", "libloaderapi"]

[target.'cfg(windows)'.build-dependencies]
windres = "0.1"
